version: '3.4'

services:
  app:
    container_name: pixelbattle-app
    image: pixelbattle-app
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        - APP_ENV=dev
        - NODE_ENV=dev
        - WORKDIR_SRC_DEFAULT=pixelbattle
    volumes:
      - "./src:/public"
      - "./app/nginx/nginx.conf.${APP_ENV-prod}:/etc/nginx/nginx.conf"
      - "./app/nginx/errors:/usr/share/nginx/html/errors"
    tty: true
    restart: unless-stopped
    ports:
      - "8080:80"   # web server (http)
      - "4443:443"  # web server (https)
    depends_on:
      - rethinkdb
    links:
      - rethinkdb:rethinkdb
    environment:
      - APP_ENV=${APP_ENV-dev}   # default value: dev
      - NODE_ENV=${APP_ENV-dev}

  rethinkdb:
    container_name: pixelbattle-rethinkdb
    image: pixelbattle-rethinkdb
    build:
      context: .
      dockerfile: rethinkdb/Dockerfile
      args:
        - APP_ENV=prod
    volumes:
      - "./rethinkdb/data:/data:rw"
      - "./rethinkdb/rethinkdb-entrypoint-db.init.sh:/rethinkdb-entrypoint-db.init.sh"
      - "./rethinkdb/scripts:/scripts"
      - "./shared-conf/env.example.dev:/.env"
    tty: true
    restart: unless-stopped
    ports:
      - "4321:8080"   # admin web-ui
      - "28015:28015" # client driver connections
      - "29015:29015" # intracluster driver connections
