version: '3.4'

services:
  rethinkdb:
    container_name: pixelbattle-rethinkdb
    image: pixelbattle-rethinkdb
    build:
      context: .
      dockerfile: rethinkdb/Dockerfile
      args:
        - APP_ENV=prod
    volumes:
      - data-volume:/data
      - "./rethinkdb/rethinkdb-entrypoint-db.init.sh:/rethinkdb-entrypoint-db.init.sh"
      - "./rethinkdb/scripts:/scripts"
      - "./shared-conf/env.example.dev:/.env"
    tty: true
    restart: unless-stopped
    ports:
      - "4321:8080"   # admin web-ui
      - "28015:28015" # client driver connections
      - "29015:29015" # intracluster driver connections
volumes:
  data-volume:
    driver: "rexray/ebs"
    name: "pixelbattle-rethinkdb-data-vol"
    driver_opts:
      volumeType: "gp2" # SSD
      size: 8           # GB
    #external:
    #  name: "pixelbattle-rethinkdb-data-vol"
