version: '3.4'

services:
  app:
    container_name: pixelbattle-app
    image: pixelbattle-app
    build:
      context: .
      dockerfile: app/Dockerfile.prod
      args:
        - APP_ENV=prod
        - NODE_ENV=prod
        - WORKDIR_SRC_DEFAULT=pixelbattle
        - APP_GIT_BRANCH=master
        - GITHUB_REPO_URL=https://github.com/cristiancmello/pixelbattle.git
    tty: true
    restart: unless-stopped
    ports:
      - "80:80"   # web server (http)
      - "443:443"  # web server (https)
    environment:
      - APP_ENV=${APP_ENV-prod}   # default value: prod
      - NODE_ENV=${APP_ENV-prod}
      - APP_GIT_BRANCH=${APP_GIT_BRANCH-master}
