version: '3.4'

services:
  app:
    container_name: pixelbattle-app
    image: pixelbattle-app
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        - APP_ENV=prod
        - NODE_ENV=prod
        - WORKDIR_SRC_DEFAULT=pixelbattle
        - APP_GIT_BRANCH=aws
    volumes:
      - "./src:/public"
      - "./app/nginx/nginx.conf.${APP_ENV-prod}:/etc/nginx/nginx.conf"
      - "./app/nginx/errors:/usr/share/nginx/html/errors"
      - "/env/.env:/public/pixelbattle/.env"
    tty: true
    restart: unless-stopped
    ports:
      - "8080:80" # web server
    environment:
      - APP_ENV=${APP_ENV-prod}   # default value: prod
      - NODE_ENV=${APP_ENV-prod}
      - APP_GIT_BRANCH=${APP_GIT_BRANCH-aws}
