version: '3.4'

services:
  api:
    container_name: dev-pixelbattle-api
    image: dev-pixelbattle-api
    build:
        context: .
        dockerfile: api/Dockerfile
        args:
            - APP_ENV=dev
            - WORKDIR_SRC_DEFAULT=pixelbattle
    volumes:
        - "./src:/public"
        - "./api/nginx/nginx.conf:/etc/nginx/nginx.conf"
        - "./api/nginx/errors:/usr/share/nginx/html/errors"
    tty: true
    restart: unless-stopped
    ports:
        - "8080:80"