version: '3.4'

services:
  api:
    container_name: pixelbattle-api
    image: pixelbattle-api
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        - APP_ENV=prod
        - NODE_ENV=prod
        - WORKDIR_SRC_DEFAULT=pixelbattle
    volumes:
      - "./src:/public"
      - "./api/nginx/nginx.conf.${APP_ENV-prod}:/etc/nginx/nginx.conf"
      - "./api/nginx/errors:/usr/share/nginx/html/errors"
    tty: true
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - rethinkdb
    links:
      - rethinkdb:rethinkdb
    environment:
      - APP_ENV=${APP_ENV-prod}   # default value: prod
      - NODE_ENV=${APP_ENV-prod}

  rethinkdb:
    container_name: pixelbattle-rethinkdb
    image: pixelbattle-rethinkdb
    build:
      context: .
      dockerfile: rethinkdb/Dockerfile
      args:
        - APP_ENV=prod
    volumes:
      - "./rethinkdb/data:/data:rw"
    tty: true
    restart: unless-stopped
    ports:
      - "4321:8080"   # admin web-ui
      - "28015:28015" # client driver connections
      - "29015:29015" # intracluster driver connections